services:
  kuzco-main:
    container_name: kuzco-inference
    # image: zkproxy/kuzco-vikey # optional
    build: .
    networks:
      - kuzco-network
    restart: always
    env_file: .env
    environment:
      NODE_ENV: "production"
      CODE: "${WORKER_CODE}"
      WORKER_NAME: "${WORKER_NAME}"
      VIKEY_API_KEY: "${VIKEY_API_KEY}"
    volumes:
      - /var/lib/docker/containers:/host/docker/containers:ro  # Mount log Docker read-only

networks:
  kuzco-network:
    driver: bridge