services:
  kuzco-main:
    container_name: kuzco-inference
    # image: zkproxy/kuzco-vikey # optional
    build: .
    networks:
      - kuzco-network
    restart: always
    env_file: .env
    environment:
      NODE_ENV: "production"
      CODE: "${WORKER_CODE}"
      WORKER_NAME: "${WORKER_NAME}"
      # GPU0_UID: "${GPU0_UID}"
      VIKEY_API_KEY: "${VIKEY_API_KEY}"

networks:
  kuzco-network:
    driver: bridge
