services:
  kuzco-main:
    container_name: kuzco-inference
    # image: zkproxy/kuzco-vikey # optional
    build: .
    networks:
      - kuzco-network
    restart: always
    env_file: .env
    environment:
      NODE_ENV: "production"
      CODE: "${WORKER_CODE}"
      WORKER_NAME: "${WORKER_NAME}"
      VIKEY_API_KEY: "${VIKEY_API_KEY}"
    ports:
      - "5050:5050"
    volumes:
      - ./kuzco.log:/app/kuzco-inference/vikey-inference/kuzco.log
      - ./home/monitoring:/app/monitoring

networks:
  kuzco-network:
    driver: bridge
